// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7h76DHMdY2ta7qO6LZBCJDroo3ls0jTs',
    appId: '1:82468183110:web:d06f370a1dcbd800e17e47',
    messagingSenderId: '82468183110',
    projectId: 'halaqoh-15f2e',
    authDomain: 'halaqoh-15f2e.firebaseapp.com',
    storageBucket: 'halaqoh-15f2e.appspot.com',
    measurementId: 'G-077CQ9ZC00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlU6xjdCPq2AzbFGr-Uk1ShvCBZh6qyMM',
    appId: '1:82468183110:android:42378c2d8ad5fb1fe17e47',
    messagingSenderId: '82468183110',
    projectId: 'halaqoh-15f2e',
    storageBucket: 'halaqoh-15f2e.appspot.com',
  );
}
